import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialMigration1749124583295 implements MigrationInterface {
    name = 'InitialMigration1749124583295'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "review_response" ("id" SERIAL NOT NULL, "message" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "reviewId" integer, "responderId" integer, CONSTRAINT "PK_d645699515ee36a4a26b90fd545" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "review" ("id" SERIAL NOT NULL, "rating" integer NOT NULL, "approved" boolean NOT NULL DEFAULT false, "helpfulVotes" integer NOT NULL DEFAULT '0', "productId" integer, "serviceId" integer, "content" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" integer, CONSTRAINT "PK_2e4299a343a81574217255c00ca" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."customer_addresses_type_enum" AS ENUM('HOME', 'WORK', 'BILLING', 'SHIPPING', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "customer_addresses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customerId" uuid NOT NULL, "type" "public"."customer_addresses_type_enum" NOT NULL DEFAULT 'HOME', "street" character varying(255) NOT NULL, "city" character varying(100) NOT NULL, "state" character varying(100) NOT NULL, "postalCode" character varying(20) NOT NULL, "country" character varying(100) NOT NULL, "isPrimary" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, "latitude" numeric(10,8), "longitude" numeric(11,8), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_336bda7b0a0cd04241f719fc834" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "loyalty_point" ("id" SERIAL NOT NULL, "points" integer NOT NULL, "type" character varying NOT NULL, "date" TIMESTAMP NOT NULL DEFAULT now(), "description" character varying, "customerId" uuid, CONSTRAINT "PK_d639711df65f35a798b58c7b3f8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "items" jsonb NOT NULL, "total" numeric NOT NULL, "status" character varying NOT NULL DEFAULT 'pending', "paymentId" character varying, "paymentStatus" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "customerId" uuid, CONSTRAINT "PK_1031171c13130102495201e3e20" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."subscription_plan_billingcycle_enum" AS ENUM('weekly', 'monthly', 'quarterly', 'yearly')`);
        await queryRunner.query(`CREATE TABLE "subscription_plan" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text NOT NULL, "price" numeric(10,2) NOT NULL, "billingCycle" "public"."subscription_plan_billingcycle_enum" NOT NULL, "deliveryFrequency" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "productIds" text NOT NULL, "features" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5fde988e5d9b9a522d70ebec27c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."subscription_status_enum" AS ENUM('active', 'paused', 'cancelled', 'expired')`);
        await queryRunner.query(`CREATE TABLE "subscription" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" "public"."subscription_status_enum" NOT NULL DEFAULT 'active', "startDate" date NOT NULL, "endDate" date, "billingDay" integer NOT NULL, "customizations" json, "nextBillingDate" date, "lastPaymentDate" date, "paymentFailureCount" integer, "lastPaymentError" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "customerId" uuid, "planId" uuid, CONSTRAINT "PK_8c3e00ebd02103caa1174cd5d9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "amount" numeric(10,2) NOT NULL, "currency" character varying NOT NULL, "paymentMethod" character varying NOT NULL, "status" character varying NOT NULL, "transactionId" character varying, "paymentDetails" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "customerId" uuid, "orderId" uuid, "subscriptionId" uuid, CONSTRAINT "PK_fcaec7df5adf9cac408c686b2ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."customers_customertype_enum" AS ENUM('INDIVIDUAL', 'BUSINESS')`);
        await queryRunner.query(`CREATE TYPE "public"."customers_status_enum" AS ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED')`);
        await queryRunner.query(`CREATE TABLE "customers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "firstName" character varying(100) NOT NULL, "lastName" character varying(100) NOT NULL, "email" character varying(255) NOT NULL, "phoneNumber" character varying(20), "dateOfBirth" date, "customerType" "public"."customers_customertype_enum" NOT NULL DEFAULT 'INDIVIDUAL', "status" "public"."customers_status_enum" NOT NULL DEFAULT 'ACTIVE', "notes" character varying(500), "isEmailVerified" boolean NOT NULL DEFAULT false, "isPhoneVerified" boolean NOT NULL DEFAULT false, "lastLoginAt" TIMESTAMP, "emergencyContactName" character varying(255), "emergencyContactPhone" character varying(20), "emergencyContactRelation" character varying(100), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8536b8b85c06969f84f0c098b03" UNIQUE ("email"), CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."pricing_packages_type_enum" AS ENUM('basic', 'standard', 'premium', 'luxury')`);
        await queryRunner.query(`CREATE TABLE "pricing_packages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "facilityId" uuid NOT NULL, "name" character varying(255) NOT NULL, "description" text NOT NULL, "type" "public"."pricing_packages_type_enum" NOT NULL DEFAULT 'basic', "dailyRate" numeric(10,2) NOT NULL, "weeklyRate" numeric(10,2), "monthlyRate" numeric(10,2), "includedServices" json NOT NULL, "additionalServices" json, "maxPetSize" integer, "allowedPetTypes" json, "minBookingDays" integer, "maxBookingDays" integer, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9e48469a36e2290a77ecd4885c3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "boarding_facilities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "description" text NOT NULL, "address" text NOT NULL, "phone" character varying(20) NOT NULL, "email" character varying(255) NOT NULL, "capacity" integer NOT NULL, "currentOccupancy" integer NOT NULL DEFAULT '0', "amenities" json, "operatingHours" json, "website" text, "latitude" numeric(10,6), "longitude" numeric(10,6), "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6f2c222b2698409d82249194206" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."activities_type_enum" AS ENUM('feeding', 'walking', 'playtime', 'grooming', 'medication', 'veterinary', 'exercise', 'socialization', 'rest', 'training', 'other')`);
        await queryRunner.query(`CREATE TABLE "activities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "bookingId" uuid NOT NULL, "staffId" integer NOT NULL, "type" "public"."activities_type_enum" NOT NULL, "title" character varying(255) NOT NULL, "description" text NOT NULL, "activityTime" TIMESTAMP NOT NULL, "duration" integer, "metadata" json, "photoUrls" json, "isVisible" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "petId" uuid, CONSTRAINT "PK_7f4004429f731ffb9c88eb486a8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."bookings_status_enum" AS ENUM('pending', 'confirmed', 'checked_in', 'checked_out', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "bookings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "petId" uuid NOT NULL, "ownerId" integer NOT NULL, "facilityId" uuid NOT NULL, "packageId" uuid NOT NULL, "startDate" date NOT NULL, "endDate" date NOT NULL, "checkInTime" TIMESTAMP, "checkOutTime" TIMESTAMP, "status" "public"."bookings_status_enum" NOT NULL DEFAULT 'pending', "totalPrice" numeric(10,2) NOT NULL, "specialInstructions" text, "emergencyContact" text, "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bee6805982cc1e248e94ce94957" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."photos_type_enum" AS ENUM('daily_update', 'activity', 'meal_time', 'play_time', 'sleeping', 'grooming', 'check_in', 'check_out', 'medical', 'other')`);
        await queryRunner.query(`CREATE TABLE "photos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "bookingId" uuid NOT NULL, "uploadedById" integer NOT NULL, "url" text NOT NULL, "filename" character varying(255) NOT NULL, "type" "public"."photos_type_enum" NOT NULL DEFAULT 'daily_update', "caption" text, "metadata" json, "isVisible" boolean NOT NULL DEFAULT true, "isFavorite" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "petId" uuid, CONSTRAINT "PK_5220c45b8e32d49d767b9b3d725" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "medical_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" text NOT NULL, "type" character varying NOT NULL, "date" date NOT NULL, "veterinarian" character varying, "clinic" character varying, "medications" json, "notes" text, "attachments" json, "petId" uuid NOT NULL, "createdById" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b74f21cb30300ddf41a00623568" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."prescription_refills_status_enum" AS ENUM('requested', 'approved', 'fulfilled', 'denied')`);
        await queryRunner.query(`CREATE TABLE "prescription_refills" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "prescriptionId" uuid NOT NULL, "status" "public"."prescription_refills_status_enum" NOT NULL DEFAULT 'requested', "notes" text, "requestedById" integer NOT NULL, "processedById" integer, "processedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a9b54992717397e8623f48b13fb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."prescriptions_status_enum" AS ENUM('pending', 'active', 'fulfilled', 'completed', 'cancelled', 'expired')`);
        await queryRunner.query(`CREATE TABLE "prescriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "instructions" text NOT NULL, "dosage" character varying NOT NULL, "frequency" character varying NOT NULL, "startDate" date NOT NULL, "endDate" date, "duration" integer NOT NULL, "refillsAllowed" integer NOT NULL DEFAULT '0', "refillsUsed" integer NOT NULL DEFAULT '0', "status" "public"."prescriptions_status_enum" NOT NULL DEFAULT 'pending', "notes" text, "externalReferenceId" character varying, "petId" uuid NOT NULL, "veterinarianId" integer NOT NULL, "fulfilledById" integer, "fulfilledAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_097b2cc2f2b7e56825468188503" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."pets_gender_enum" AS ENUM('MALE', 'FEMALE', 'UNKNOWN')`);
        await queryRunner.query(`CREATE TYPE "public"."pets_status_enum" AS ENUM('ACTIVE', 'INACTIVE', 'DECEASED')`);
        await queryRunner.query(`CREATE TABLE "pets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customerId" uuid NOT NULL, "name" character varying(100) NOT NULL, "species" character varying(50) NOT NULL, "breed" character varying(100), "gender" "public"."pets_gender_enum" NOT NULL DEFAULT 'UNKNOWN', "dateOfBirth" date, "weight" numeric(5,2), "color" character varying(50), "microchipNumber" character varying(100), "status" "public"."pets_status_enum" NOT NULL DEFAULT 'ACTIVE', "isActive" boolean NOT NULL DEFAULT true, "notes" character varying(500), "photoUrl" character varying(255), "medicalConditions" json, "allergies" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "ownerId" integer, CONSTRAINT "PK_d01e9e7b4ada753c826720bee8b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "email" character varying(255) NOT NULL, "role" character varying NOT NULL DEFAULT 'user', "isVerified" boolean NOT NULL DEFAULT false, "password" character varying(255) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."credentials_type_enum" AS ENUM('license', 'certification', 'degree', 'continuing_education')`);
        await queryRunner.query(`CREATE TABLE "credentials" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "type" "public"."credentials_type_enum" NOT NULL, "issuingAuthority" character varying NOT NULL, "licenseNumber" character varying NOT NULL, "issueDate" date NOT NULL, "expirationDate" date NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "notes" text, "veterinarianId" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c51c51db8d8ca702ac620569d40" UNIQUE ("licenseNumber"), CONSTRAINT "PK_1e38bc43be6697cdda548ad27a6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "specializations" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "description" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_68ccfdea9eca4570f9aa5454b25" UNIQUE ("name"), CONSTRAINT "PK_1d4b2b9ff96a76def0bf7195a8f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."veterinarians_status_enum" AS ENUM('active', 'inactive', 'on_leave', 'retired')`);
        await queryRunner.query(`CREATE TABLE "veterinarians" ("id" SERIAL NOT NULL, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "email" character varying NOT NULL, "phone" character varying, "bio" text, "profileImage" character varying, "yearsOfExperience" integer NOT NULL DEFAULT '0', "status" "public"."veterinarians_status_enum" NOT NULL DEFAULT 'active', "rating" numeric(3,2) NOT NULL DEFAULT '0', "address" text, "emergencyContact" character varying, "emergencyPhone" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_1f3e55dccd32b7c120378247810" UNIQUE ("email"), CONSTRAINT "PK_a68520babb0d0d23dd052e8dc76" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."availability_schedules_dayofweek_enum" AS ENUM('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday')`);
        await queryRunner.query(`CREATE TABLE "availability_schedules" ("id" SERIAL NOT NULL, "dayOfWeek" "public"."availability_schedules_dayofweek_enum" NOT NULL, "startTime" TIME NOT NULL, "endTime" TIME NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "effectiveFrom" date, "effectiveTo" date, "veterinarianId" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cfb5fcd683ea4ea6bec3183a216" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."time_slots_status_enum" AS ENUM('available', 'booked', 'blocked', 'break', 'holiday')`);
        await queryRunner.query(`CREATE TABLE "time_slots" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "startTime" TIMESTAMP NOT NULL, "endTime" TIMESTAMP NOT NULL, "status" "public"."time_slots_status_enum" NOT NULL DEFAULT 'available', "isActive" boolean NOT NULL DEFAULT true, "appointmentId" character varying, "metadata" text, "availabilityScheduleId" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f87c73d8648c3f3f297adba3cb8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cart_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "cartId" uuid NOT NULL, "productId" uuid NOT NULL, "productName" character varying NOT NULL, "price" numeric(10,2) NOT NULL, "quantity" integer NOT NULL DEFAULT '1', "subtotal" numeric(10,2) NOT NULL, CONSTRAINT "PK_6fccf5ec03c172d27a28a82928b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "carts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid, "sessionId" character varying, "totalAmount" numeric(10,2) NOT NULL DEFAULT '0', "totalItems" integer NOT NULL DEFAULT '0', "expiresAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b5f695a59f5ebb50af3c8160816" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_variants" ("id" SERIAL NOT NULL, "size" character varying NOT NULL, "color" character varying NOT NULL, "sku" character varying NOT NULL, "priceAdjustment" numeric(10,2), "stockQuantity" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "product_id" integer, CONSTRAINT "UQ_46f236f21640f9da218a063a866" UNIQUE ("sku"), CONSTRAINT "PK_281e3f2c55652d6a22c0aa59fd7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_images" ("id" SERIAL NOT NULL, "filename" character varying NOT NULL, "originalName" character varying NOT NULL, "mimeType" character varying NOT NULL, "size" integer NOT NULL, "url" character varying NOT NULL, "isPrimary" boolean NOT NULL DEFAULT false, "sortOrder" integer NOT NULL DEFAULT '0', "product_id" integer, CONSTRAINT "PK_1974264ea7265989af8392f63a1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "inventory" ("id" SERIAL NOT NULL, "stockQuantity" integer NOT NULL DEFAULT '0', "reservedQuantity" integer NOT NULL DEFAULT '0', "reorderLevel" integer NOT NULL DEFAULT '0', "maxStockLevel" integer NOT NULL DEFAULT '0', "lastUpdated" TIMESTAMP NOT NULL DEFAULT now(), "product_id" integer, CONSTRAINT "REL_732fdb1f76432d65d2c136340d" UNIQUE ("product_id"), CONSTRAINT "PK_82aa5da437c5bbfb80703b08309" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "products" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "description" text NOT NULL, "price" numeric(10,2) NOT NULL, "sku" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "category_id" integer, CONSTRAINT "UQ_c44ac33a05b144dd0d9ddcf9327" UNIQUE ("sku"), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "categories" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "description" character varying, "image" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "parent_id" integer, CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."stock_movements_movementtype_enum" AS ENUM('RECEIPT', 'ISSUE', 'TRANSFER_IN', 'TRANSFER_OUT', 'ADJUSTMENT', 'RETURN', 'DAMAGE', 'EXPIRED')`);
        await queryRunner.query(`CREATE TABLE "stock_movements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "inventoryItemId" uuid NOT NULL, "movementType" "public"."stock_movements_movementtype_enum" NOT NULL, "quantity" integer NOT NULL, "previousStock" integer NOT NULL, "newStock" integer NOT NULL, "referenceNumber" character varying(100), "notes" text, "userId" uuid, "ipAddress" character varying(45), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_57a26b190618550d8e65fb860e7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."stock_alerts_alerttype_enum" AS ENUM('LOW_STOCK', 'OUT_OF_STOCK', 'OVERSTOCK', 'EXPIRY_WARNING')`);
        await queryRunner.query(`CREATE TYPE "public"."stock_alerts_status_enum" AS ENUM('ACTIVE', 'ACKNOWLEDGED', 'RESOLVED')`);
        await queryRunner.query(`CREATE TABLE "stock_alerts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "inventoryItemId" uuid NOT NULL, "alertType" "public"."stock_alerts_alerttype_enum" NOT NULL, "thresholdValue" integer, "status" "public"."stock_alerts_status_enum" NOT NULL DEFAULT 'ACTIVE', "isActive" boolean NOT NULL DEFAULT true, "lastTriggered" TIMESTAMP, "acknowledgedBy" uuid, "acknowledgedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3c3bb550b3bf192460bffe3a55b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "inventory_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sku" character varying(50) NOT NULL, "name" character varying(255) NOT NULL, "description" text, "categoryId" uuid, "unitOfMeasure" character varying(20) NOT NULL DEFAULT 'piece', "currentStock" integer NOT NULL DEFAULT '0', "reservedStock" integer NOT NULL DEFAULT '0', "reorderPoint" integer, "maxStockLevel" integer, "unitCost" numeric(10,2), "sellingPrice" numeric(10,2), "supplierId" uuid, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_395ec8d9e0cad6e3890b989fc1c" UNIQUE ("sku"), CONSTRAINT "PK_cf2f451407242e132547ac19169" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "insurance_providers" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "code" character varying NOT NULL, "apiEndpoint" character varying NOT NULL, "apiKey" character varying NOT NULL, "configuration" json, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_5d8cf29c67345b3e175e85e2219" UNIQUE ("name"), CONSTRAINT "PK_1b917328814bb47bfdf32f01a0a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."insurance_policies_status_enum" AS ENUM('active', 'suspended', 'cancelled', 'expired')`);
        await queryRunner.query(`CREATE TABLE "insurance_policies" ("id" SERIAL NOT NULL, "policyNumber" character varying NOT NULL, "holderName" character varying NOT NULL, "holderEmail" character varying NOT NULL, "holderPhone" character varying NOT NULL, "deductible" numeric(10,2) NOT NULL, "coveragePercentage" numeric(5,2) NOT NULL, "annualLimit" numeric(10,2) NOT NULL, "effectiveDate" date NOT NULL, "expirationDate" date NOT NULL, "status" "public"."insurance_policies_status_enum" NOT NULL DEFAULT 'active', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "provider_id" integer NOT NULL, "pet_id" uuid NOT NULL, CONSTRAINT "UQ_baa50eb26aac0be1b692c080fbf" UNIQUE ("policyNumber"), CONSTRAINT "PK_69af1d3a19277d1a822c9b13bf1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."claim_documents_documenttype_enum" AS ENUM('invoice', 'medical_record', 'prescription', 'lab_result', 'other')`);
        await queryRunner.query(`CREATE TABLE "claim_documents" ("id" SERIAL NOT NULL, "fileName" character varying NOT NULL, "originalName" character varying NOT NULL, "mimeType" character varying NOT NULL, "fileSize" integer NOT NULL, "filePath" character varying NOT NULL, "documentType" "public"."claim_documents_documenttype_enum" NOT NULL, "uploadedAt" TIMESTAMP NOT NULL DEFAULT now(), "claim_id" integer NOT NULL, CONSTRAINT "PK_926ac9a44ec173769f00b65b841" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."pre_authorizations_status_enum" AS ENUM('pending', 'approved', 'denied', 'expired')`);
        await queryRunner.query(`CREATE TABLE "pre_authorizations" ("id" SERIAL NOT NULL, "authorizationNumber" character varying NOT NULL, "treatmentType" character varying NOT NULL, "treatmentDescription" text NOT NULL, "estimatedCost" numeric(10,2) NOT NULL, "authorizedAmount" numeric(10,2), "status" "public"."pre_authorizations_status_enum" NOT NULL DEFAULT 'pending', "expirationDate" date NOT NULL, "notes" text, "providerResponse" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "policy_id" integer NOT NULL, CONSTRAINT "UQ_95e320ead48fab8d143f6dea3d6" UNIQUE ("authorizationNumber"), CONSTRAINT "PK_0879f27cdeb80ae15a87765e0f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."insurance_claims_status_enum" AS ENUM('draft', 'submitted', 'under_review', 'approved', 'denied', 'paid', 'partially_paid')`);
        await queryRunner.query(`CREATE TABLE "insurance_claims" ("id" SERIAL NOT NULL, "claimNumber" character varying NOT NULL, "treatmentDate" TIMESTAMP NOT NULL, "diagnosis" character varying NOT NULL, "treatmentDescription" text NOT NULL, "totalAmount" numeric(10,2) NOT NULL, "approvedAmount" numeric(10,2), "paidAmount" numeric(10,2), "status" "public"."insurance_claims_status_enum" NOT NULL DEFAULT 'draft', "denialReason" text, "veterinarianName" character varying NOT NULL, "veterinarianLicense" character varying NOT NULL, "clinicName" character varying NOT NULL, "clinicAddress" character varying NOT NULL, "providerResponse" json, "submittedAt" TIMESTAMP, "processedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "policy_id" integer NOT NULL, "pre_authorization_id" integer, CONSTRAINT "UQ_7c69728b0eee8df90aa28cb3aaf" UNIQUE ("claimNumber"), CONSTRAINT "PK_c6f7929fdcec8c17a24034a48d3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "grooming_packages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text NOT NULL, "price" numeric NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_46b5ae3f7f7c1552872a7f0ceb9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."grooming_appointments_status_enum" AS ENUM('PENDING', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "grooming_appointments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "petId" character varying NOT NULL, "packageId" uuid NOT NULL, "appointmentTime" TIMESTAMP NOT NULL, "status" "public"."grooming_appointments_status_enum" NOT NULL DEFAULT 'IN_PROGRESS', "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e1918f79bf721eb472cda3971a3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."emergency_appointments_priority_enum" AS ENUM('CRITICAL', 'HIGH', 'MEDIUM', 'LOW')`);
        await queryRunner.query(`CREATE TYPE "public"."emergency_appointments_status_enum" AS ENUM('PENDING', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TYPE "public"."emergency_appointments_triagelevel_enum" AS ENUM('1', '2', '3', '4')`);
        await queryRunner.query(`CREATE TABLE "emergency_appointments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "petName" character varying NOT NULL, "petSpecies" character varying NOT NULL, "petAge" integer NOT NULL, "ownerName" character varying NOT NULL, "ownerPhone" character varying NOT NULL, "ownerEmail" character varying NOT NULL, "emergencyContactPhone" character varying NOT NULL, "symptoms" text NOT NULL, "additionalNotes" text, "priority" "public"."emergency_appointments_priority_enum" NOT NULL DEFAULT 'MEDIUM', "status" "public"."emergency_appointments_status_enum" NOT NULL DEFAULT 'PENDING', "triageLevel" "public"."emergency_appointments_triagelevel_enum" NOT NULL DEFAULT '4', "estimatedCost" numeric(10,2), "scheduledTime" TIMESTAMP, "arrivalTime" TIMESTAMP, "emergencyContactNotified" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b1a667a7520214dfded43c87be5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "audit_log" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user" character varying NOT NULL, "action" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, CONSTRAINT "PK_07fefa57f7f5ab8fc3f52b3ed0b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "config_entity" ("key" character varying NOT NULL, "maintenanceMode" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_343ec12d098643a80c3a17b0541" PRIMARY KEY ("key"))`);
        await queryRunner.query(`CREATE TABLE "pet_family_members" ("petId" uuid NOT NULL, "userId" integer NOT NULL, CONSTRAINT "PK_a9121160f4715bac9a43ef2701c" PRIMARY KEY ("petId", "userId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4cc693a026b769113e348e1bbd" ON "pet_family_members" ("petId") `);
        await queryRunner.query(`CREATE INDEX "IDX_75f441f4936101c0b0abcda3a5" ON "pet_family_members" ("userId") `);
        await queryRunner.query(`CREATE TABLE "veterinarian_specializations" ("veterinarianId" integer NOT NULL, "specializationId" integer NOT NULL, CONSTRAINT "PK_b6f9bea967fa6cc71be0a93f86c" PRIMARY KEY ("veterinarianId", "specializationId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2618e3df4b2e40d647dc8e10ad" ON "veterinarian_specializations" ("veterinarianId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1a97aa34592a6bda0f2c188b80" ON "veterinarian_specializations" ("specializationId") `);
        await queryRunner.query(`ALTER TABLE "review_response" ADD CONSTRAINT "FK_b2f60473130d8d921e970307cca" FOREIGN KEY ("reviewId") REFERENCES "review"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "review_response" ADD CONSTRAINT "FK_adbe77011fe66e1f63d0ea9b39d" FOREIGN KEY ("responderId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "review" ADD CONSTRAINT "FK_1337f93918c70837d3cea105d39" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_addresses" ADD CONSTRAINT "FK_7bd088b1c8d3506953240ebf030" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loyalty_point" ADD CONSTRAINT "FK_459d7cb0f005a23c1732b4bd921" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_124456e637cca7a415897dce659" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription" ADD CONSTRAINT "FK_e4543f99d629cf2c04fe9332e30" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription" ADD CONSTRAINT "FK_6b6d0e4dc88105a4a11103dd2cd" FOREIGN KEY ("planId") REFERENCES "subscription_plan"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment" ADD CONSTRAINT "FK_967ae37468fd0c08ea0fec41720" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment" ADD CONSTRAINT "FK_d09d285fe1645cd2f0db811e293" FOREIGN KEY ("orderId") REFERENCES "order"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment" ADD CONSTRAINT "FK_25f06021d5e959312ce6fabe3c7" FOREIGN KEY ("subscriptionId") REFERENCES "subscription"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pricing_packages" ADD CONSTRAINT "FK_60594f8849e3b591559280f54b2" FOREIGN KEY ("facilityId") REFERENCES "boarding_facilities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activities" ADD CONSTRAINT "FK_6db49ca83bc69011d2128ce801f" FOREIGN KEY ("petId") REFERENCES "pets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activities" ADD CONSTRAINT "FK_f33bdfe28c64bf59bf75b6d321d" FOREIGN KEY ("bookingId") REFERENCES "bookings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activities" ADD CONSTRAINT "FK_31490029908cef2b775519b7148" FOREIGN KEY ("staffId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_94644337cd37374b24f1f89ef72" FOREIGN KEY ("petId") REFERENCES "pets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_85001d7223966f1b05d302d7807" FOREIGN KEY ("ownerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_26ac8c3a8ad4bf675fab70e46ff" FOREIGN KEY ("facilityId") REFERENCES "boarding_facilities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_c33a993088cbe955492d812b1b2" FOREIGN KEY ("packageId") REFERENCES "pricing_packages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "photos" ADD CONSTRAINT "FK_ebda8174dc87b07c7a838740c4b" FOREIGN KEY ("petId") REFERENCES "pets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "photos" ADD CONSTRAINT "FK_362e2120225c9aaa2df20fb71d9" FOREIGN KEY ("bookingId") REFERENCES "bookings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "photos" ADD CONSTRAINT "FK_555e65a79c560d678712a3aec1e" FOREIGN KEY ("uploadedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "medical_history" ADD CONSTRAINT "FK_8f6640186fa4cd75de1dc424dc4" FOREIGN KEY ("petId") REFERENCES "pets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "medical_history" ADD CONSTRAINT "FK_13a4d5a181936c37e13fca2f0eb" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prescription_refills" ADD CONSTRAINT "FK_706a1a9ad68516fdcb992704033" FOREIGN KEY ("prescriptionId") REFERENCES "prescriptions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prescription_refills" ADD CONSTRAINT "FK_0d0480435b46ffd4ca71b1291fe" FOREIGN KEY ("requestedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prescription_refills" ADD CONSTRAINT "FK_2cae0f144dc7bfce56fd7dc9ff4" FOREIGN KEY ("processedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prescriptions" ADD CONSTRAINT "FK_b078a14ba386425bea287fed17b" FOREIGN KEY ("petId") REFERENCES "pets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prescriptions" ADD CONSTRAINT "FK_ee2f1ea654dc32858642b87953c" FOREIGN KEY ("veterinarianId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prescriptions" ADD CONSTRAINT "FK_c8f5a52509a453debf468766f63" FOREIGN KEY ("fulfilledById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pets" ADD CONSTRAINT "FK_b0b20a01418c42314f6d9fe9963" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pets" ADD CONSTRAINT "FK_275e1bb3fdeea68f8356d8e1ebb" FOREIGN KEY ("ownerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credentials" ADD CONSTRAINT "FK_73eebb8602465640f7a1c4e236b" FOREIGN KEY ("veterinarianId") REFERENCES "veterinarians"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "availability_schedules" ADD CONSTRAINT "FK_bed627405148ce1a7cddf60f81d" FOREIGN KEY ("veterinarianId") REFERENCES "veterinarians"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "time_slots" ADD CONSTRAINT "FK_bca527efc56ec488f8cc7d09ce5" FOREIGN KEY ("availabilityScheduleId") REFERENCES "availability_schedules"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_edd714311619a5ad09525045838" FOREIGN KEY ("cartId") REFERENCES "carts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD CONSTRAINT "FK_6343513e20e2deab45edfce1316" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_images" ADD CONSTRAINT "FK_4f166bb8c2bfcef2498d97b4068" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD CONSTRAINT "FK_732fdb1f76432d65d2c136340dc" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_9a5f6868c96e0069e699f33e124" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_88cea2dc9c31951d06437879b40" FOREIGN KEY ("parent_id") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "FK_769feb209282a3f34e42d89f1dd" FOREIGN KEY ("inventoryItemId") REFERENCES "inventory_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_alerts" ADD CONSTRAINT "FK_2f75c96949ead9e826cab9de3ff" FOREIGN KEY ("inventoryItemId") REFERENCES "inventory_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insurance_policies" ADD CONSTRAINT "FK_2e43f57ec047088040442585256" FOREIGN KEY ("provider_id") REFERENCES "insurance_providers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insurance_policies" ADD CONSTRAINT "FK_373425fb1215850d4a5f3afc087" FOREIGN KEY ("pet_id") REFERENCES "pets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "claim_documents" ADD CONSTRAINT "FK_9dfdd8ea365fd3699275a15b1c7" FOREIGN KEY ("claim_id") REFERENCES "insurance_claims"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pre_authorizations" ADD CONSTRAINT "FK_5cc556bc1b50856140daecefc3b" FOREIGN KEY ("policy_id") REFERENCES "insurance_policies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insurance_claims" ADD CONSTRAINT "FK_8a4ca31994dc7685cd9cf7943c4" FOREIGN KEY ("policy_id") REFERENCES "insurance_policies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insurance_claims" ADD CONSTRAINT "FK_7dcd2b96dfa1b0f1bf3009efd3c" FOREIGN KEY ("pre_authorization_id") REFERENCES "pre_authorizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grooming_appointments" ADD CONSTRAINT "FK_d0076fd00dc816a1cca182b25a3" FOREIGN KEY ("packageId") REFERENCES "grooming_packages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pet_family_members" ADD CONSTRAINT "FK_4cc693a026b769113e348e1bbd0" FOREIGN KEY ("petId") REFERENCES "pets"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "pet_family_members" ADD CONSTRAINT "FK_75f441f4936101c0b0abcda3a5f" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "veterinarian_specializations" ADD CONSTRAINT "FK_2618e3df4b2e40d647dc8e10adb" FOREIGN KEY ("veterinarianId") REFERENCES "veterinarians"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "veterinarian_specializations" ADD CONSTRAINT "FK_1a97aa34592a6bda0f2c188b80a" FOREIGN KEY ("specializationId") REFERENCES "specializations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "veterinarian_specializations" DROP CONSTRAINT "FK_1a97aa34592a6bda0f2c188b80a"`);
        await queryRunner.query(`ALTER TABLE "veterinarian_specializations" DROP CONSTRAINT "FK_2618e3df4b2e40d647dc8e10adb"`);
        await queryRunner.query(`ALTER TABLE "pet_family_members" DROP CONSTRAINT "FK_75f441f4936101c0b0abcda3a5f"`);
        await queryRunner.query(`ALTER TABLE "pet_family_members" DROP CONSTRAINT "FK_4cc693a026b769113e348e1bbd0"`);
        await queryRunner.query(`ALTER TABLE "grooming_appointments" DROP CONSTRAINT "FK_d0076fd00dc816a1cca182b25a3"`);
        await queryRunner.query(`ALTER TABLE "insurance_claims" DROP CONSTRAINT "FK_7dcd2b96dfa1b0f1bf3009efd3c"`);
        await queryRunner.query(`ALTER TABLE "insurance_claims" DROP CONSTRAINT "FK_8a4ca31994dc7685cd9cf7943c4"`);
        await queryRunner.query(`ALTER TABLE "pre_authorizations" DROP CONSTRAINT "FK_5cc556bc1b50856140daecefc3b"`);
        await queryRunner.query(`ALTER TABLE "claim_documents" DROP CONSTRAINT "FK_9dfdd8ea365fd3699275a15b1c7"`);
        await queryRunner.query(`ALTER TABLE "insurance_policies" DROP CONSTRAINT "FK_373425fb1215850d4a5f3afc087"`);
        await queryRunner.query(`ALTER TABLE "insurance_policies" DROP CONSTRAINT "FK_2e43f57ec047088040442585256"`);
        await queryRunner.query(`ALTER TABLE "stock_alerts" DROP CONSTRAINT "FK_2f75c96949ead9e826cab9de3ff"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "FK_769feb209282a3f34e42d89f1dd"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_88cea2dc9c31951d06437879b40"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_9a5f6868c96e0069e699f33e124"`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP CONSTRAINT "FK_732fdb1f76432d65d2c136340dc"`);
        await queryRunner.query(`ALTER TABLE "product_images" DROP CONSTRAINT "FK_4f166bb8c2bfcef2498d97b4068"`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP CONSTRAINT "FK_6343513e20e2deab45edfce1316"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_edd714311619a5ad09525045838"`);
        await queryRunner.query(`ALTER TABLE "time_slots" DROP CONSTRAINT "FK_bca527efc56ec488f8cc7d09ce5"`);
        await queryRunner.query(`ALTER TABLE "availability_schedules" DROP CONSTRAINT "FK_bed627405148ce1a7cddf60f81d"`);
        await queryRunner.query(`ALTER TABLE "credentials" DROP CONSTRAINT "FK_73eebb8602465640f7a1c4e236b"`);
        await queryRunner.query(`ALTER TABLE "pets" DROP CONSTRAINT "FK_275e1bb3fdeea68f8356d8e1ebb"`);
        await queryRunner.query(`ALTER TABLE "pets" DROP CONSTRAINT "FK_b0b20a01418c42314f6d9fe9963"`);
        await queryRunner.query(`ALTER TABLE "prescriptions" DROP CONSTRAINT "FK_c8f5a52509a453debf468766f63"`);
        await queryRunner.query(`ALTER TABLE "prescriptions" DROP CONSTRAINT "FK_ee2f1ea654dc32858642b87953c"`);
        await queryRunner.query(`ALTER TABLE "prescriptions" DROP CONSTRAINT "FK_b078a14ba386425bea287fed17b"`);
        await queryRunner.query(`ALTER TABLE "prescription_refills" DROP CONSTRAINT "FK_2cae0f144dc7bfce56fd7dc9ff4"`);
        await queryRunner.query(`ALTER TABLE "prescription_refills" DROP CONSTRAINT "FK_0d0480435b46ffd4ca71b1291fe"`);
        await queryRunner.query(`ALTER TABLE "prescription_refills" DROP CONSTRAINT "FK_706a1a9ad68516fdcb992704033"`);
        await queryRunner.query(`ALTER TABLE "medical_history" DROP CONSTRAINT "FK_13a4d5a181936c37e13fca2f0eb"`);
        await queryRunner.query(`ALTER TABLE "medical_history" DROP CONSTRAINT "FK_8f6640186fa4cd75de1dc424dc4"`);
        await queryRunner.query(`ALTER TABLE "photos" DROP CONSTRAINT "FK_555e65a79c560d678712a3aec1e"`);
        await queryRunner.query(`ALTER TABLE "photos" DROP CONSTRAINT "FK_362e2120225c9aaa2df20fb71d9"`);
        await queryRunner.query(`ALTER TABLE "photos" DROP CONSTRAINT "FK_ebda8174dc87b07c7a838740c4b"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_c33a993088cbe955492d812b1b2"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_26ac8c3a8ad4bf675fab70e46ff"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_85001d7223966f1b05d302d7807"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_94644337cd37374b24f1f89ef72"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP CONSTRAINT "FK_31490029908cef2b775519b7148"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP CONSTRAINT "FK_f33bdfe28c64bf59bf75b6d321d"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP CONSTRAINT "FK_6db49ca83bc69011d2128ce801f"`);
        await queryRunner.query(`ALTER TABLE "pricing_packages" DROP CONSTRAINT "FK_60594f8849e3b591559280f54b2"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP CONSTRAINT "FK_25f06021d5e959312ce6fabe3c7"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP CONSTRAINT "FK_d09d285fe1645cd2f0db811e293"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP CONSTRAINT "FK_967ae37468fd0c08ea0fec41720"`);
        await queryRunner.query(`ALTER TABLE "subscription" DROP CONSTRAINT "FK_6b6d0e4dc88105a4a11103dd2cd"`);
        await queryRunner.query(`ALTER TABLE "subscription" DROP CONSTRAINT "FK_e4543f99d629cf2c04fe9332e30"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_124456e637cca7a415897dce659"`);
        await queryRunner.query(`ALTER TABLE "loyalty_point" DROP CONSTRAINT "FK_459d7cb0f005a23c1732b4bd921"`);
        await queryRunner.query(`ALTER TABLE "customer_addresses" DROP CONSTRAINT "FK_7bd088b1c8d3506953240ebf030"`);
        await queryRunner.query(`ALTER TABLE "review" DROP CONSTRAINT "FK_1337f93918c70837d3cea105d39"`);
        await queryRunner.query(`ALTER TABLE "review_response" DROP CONSTRAINT "FK_adbe77011fe66e1f63d0ea9b39d"`);
        await queryRunner.query(`ALTER TABLE "review_response" DROP CONSTRAINT "FK_b2f60473130d8d921e970307cca"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1a97aa34592a6bda0f2c188b80"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2618e3df4b2e40d647dc8e10ad"`);
        await queryRunner.query(`DROP TABLE "veterinarian_specializations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_75f441f4936101c0b0abcda3a5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4cc693a026b769113e348e1bbd"`);
        await queryRunner.query(`DROP TABLE "pet_family_members"`);
        await queryRunner.query(`DROP TABLE "config_entity"`);
        await queryRunner.query(`DROP TABLE "audit_log"`);
        await queryRunner.query(`DROP TABLE "emergency_appointments"`);
        await queryRunner.query(`DROP TYPE "public"."emergency_appointments_triagelevel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."emergency_appointments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."emergency_appointments_priority_enum"`);
        await queryRunner.query(`DROP TABLE "grooming_appointments"`);
        await queryRunner.query(`DROP TYPE "public"."grooming_appointments_status_enum"`);
        await queryRunner.query(`DROP TABLE "grooming_packages"`);
        await queryRunner.query(`DROP TABLE "insurance_claims"`);
        await queryRunner.query(`DROP TYPE "public"."insurance_claims_status_enum"`);
        await queryRunner.query(`DROP TABLE "pre_authorizations"`);
        await queryRunner.query(`DROP TYPE "public"."pre_authorizations_status_enum"`);
        await queryRunner.query(`DROP TABLE "claim_documents"`);
        await queryRunner.query(`DROP TYPE "public"."claim_documents_documenttype_enum"`);
        await queryRunner.query(`DROP TABLE "insurance_policies"`);
        await queryRunner.query(`DROP TYPE "public"."insurance_policies_status_enum"`);
        await queryRunner.query(`DROP TABLE "insurance_providers"`);
        await queryRunner.query(`DROP TABLE "inventory_items"`);
        await queryRunner.query(`DROP TABLE "stock_alerts"`);
        await queryRunner.query(`DROP TYPE "public"."stock_alerts_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."stock_alerts_alerttype_enum"`);
        await queryRunner.query(`DROP TABLE "stock_movements"`);
        await queryRunner.query(`DROP TYPE "public"."stock_movements_movementtype_enum"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TABLE "inventory"`);
        await queryRunner.query(`DROP TABLE "product_images"`);
        await queryRunner.query(`DROP TABLE "product_variants"`);
        await queryRunner.query(`DROP TABLE "carts"`);
        await queryRunner.query(`DROP TABLE "cart_items"`);
        await queryRunner.query(`DROP TABLE "time_slots"`);
        await queryRunner.query(`DROP TYPE "public"."time_slots_status_enum"`);
        await queryRunner.query(`DROP TABLE "availability_schedules"`);
        await queryRunner.query(`DROP TYPE "public"."availability_schedules_dayofweek_enum"`);
        await queryRunner.query(`DROP TABLE "veterinarians"`);
        await queryRunner.query(`DROP TYPE "public"."veterinarians_status_enum"`);
        await queryRunner.query(`DROP TABLE "specializations"`);
        await queryRunner.query(`DROP TABLE "credentials"`);
        await queryRunner.query(`DROP TYPE "public"."credentials_type_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "pets"`);
        await queryRunner.query(`DROP TYPE "public"."pets_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."pets_gender_enum"`);
        await queryRunner.query(`DROP TABLE "prescriptions"`);
        await queryRunner.query(`DROP TYPE "public"."prescriptions_status_enum"`);
        await queryRunner.query(`DROP TABLE "prescription_refills"`);
        await queryRunner.query(`DROP TYPE "public"."prescription_refills_status_enum"`);
        await queryRunner.query(`DROP TABLE "medical_history"`);
        await queryRunner.query(`DROP TABLE "photos"`);
        await queryRunner.query(`DROP TYPE "public"."photos_type_enum"`);
        await queryRunner.query(`DROP TABLE "bookings"`);
        await queryRunner.query(`DROP TYPE "public"."bookings_status_enum"`);
        await queryRunner.query(`DROP TABLE "activities"`);
        await queryRunner.query(`DROP TYPE "public"."activities_type_enum"`);
        await queryRunner.query(`DROP TABLE "boarding_facilities"`);
        await queryRunner.query(`DROP TABLE "pricing_packages"`);
        await queryRunner.query(`DROP TYPE "public"."pricing_packages_type_enum"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`DROP TYPE "public"."customers_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."customers_customertype_enum"`);
        await queryRunner.query(`DROP TABLE "payment"`);
        await queryRunner.query(`DROP TABLE "subscription"`);
        await queryRunner.query(`DROP TYPE "public"."subscription_status_enum"`);
        await queryRunner.query(`DROP TABLE "subscription_plan"`);
        await queryRunner.query(`DROP TYPE "public"."subscription_plan_billingcycle_enum"`);
        await queryRunner.query(`DROP TABLE "order"`);
        await queryRunner.query(`DROP TABLE "loyalty_point"`);
        await queryRunner.query(`DROP TABLE "customer_addresses"`);
        await queryRunner.query(`DROP TYPE "public"."customer_addresses_type_enum"`);
        await queryRunner.query(`DROP TABLE "review"`);
        await queryRunner.query(`DROP TABLE "review_response"`);
    }

}
